name: "S3-compatible Sync Action"
description: "Sync a directory to an S3-compatible storage"
author: michaelliao
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
